functions

diff --git a/.github/workflows/9-Functions.yml b/.github/workflows/9-Functions.yml
--- a/.github/workflows/9-Functions.yml
+++ b/.github/workflows/9-Functions.yml
@@ -18,19 +18,21 @@ jobs:
       - name: Bug step
         if: ${{ !cancelled() && contains(github.event.pull_request.title, 'fix') }}
         run: echo "I am a bug fix"
-    #   - name: Sleep for 20 seconds
-    #     run: sleep 20
-    #   - name: Failing step
-    #     run: exit 1
-    #   - name: I will be skipped
-    #     if: ${{ success() }}
-    #     run: echo "I will print if previous steps succeed."
-    #   - name: I will execute
-    #     if: ${{ failure() }}
-    #     run: echo "I will print if any previous step fails."
-    #   - name: I will execute
-    #     if: ${{ !cancelled() }}
-    #     run: echo "I will always print, except when the workflow is cancelled."
-    #   - name: I will execute when cancelled
-    #     if: ${{ cancelled() }}
-    #     run: echo "I will print if the workflow has been cancelled."
+
+        
+      - name: Sleep for 20 seconds
+        run: sleep 20
+      - name: Failing step
+        run: exit 1
+      - name: I will be skipped
+        if: ${{ success() }}
+        run: echo "I will print if previous steps succeed."
+      - name: I will execute
+        if: ${{ failure() }}
+        run: echo "I will print if any previous step fails."
+      - name: I will execute
+        if: ${{ !cancelled() }}
+        run: echo "I will always print, except when the workflow is cancelled."
+      - name: I will execute when cancelled
+        if: ${{ cancelled() }}
+        run: echo "I will print if the workflow has been cancelled."
